//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 22 17:30:40 CET 2022
//----------------------------------------------------

package zoot.analyse;

/**
 * CUP generated class containing symbol constants.
 */
public class CodesLexicaux {
    /* terminals */
    public static final int RETOURNE = 12;
    public static final int IDF = 13;
    public static final int EGAL = 8;
    public static final int CSTBOOLEENNE = 15;
    public static final int PARFERMANTE = 11;
    public static final int CSTENTIERE = 14;
    public static final int ECRIRE = 7;
    public static final int FONCTIONS = 9;
    public static final int VIRGULE = 6;
    public static final int POINTVIRGULE = 5;
    public static final int VARIABLES = 4;
    public static final int ENTIER = 17;
    public static final int EOF = 0;
    public static final int PAROUVRANTE = 10;
    public static final int error = 1;
    public static final int BOOLEEN = 16;
    public static final int DEBUT = 2;
    public static final int FIN = 3;
}

