//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 17 14:46:16 CET 2022
//----------------------------------------------------

package zoot.analyse;

/**
 * CUP generated class containing symbol constants.
 */
public class CodesLexicaux {
    /* terminals */
    public static final int FONCTIONS = 8;
    public static final int ECRIRE = 6;
    public static final int IDF = 12;
    public static final int RETOURNE = 11;
    public static final int PAROUVRANTE = 9;
    public static final int DEBUT = 2;
    public static final int PARFERMANTE = 10;
    public static final int POINTVIRGULE = 5;
    public static final int FIN = 3;
    public static final int EOF = 0;
    public static final int VARIABLES = 4;
    public static final int CSTBOOLEENNE = 14;
    public static final int EGAL = 7;
    public static final int ENTIER = 16;
    public static final int error = 1;
    public static final int CSTENTIERE = 13;
    public static final int BOOLEEN = 15;
}

